### PR TITLE
Add using a custom main .mbedignore

### LINKED ISSUE #28: Add passing `.mbedignore` to `configure_for_target.py`
Passing `.mbedignore` would allow using this project as a pure git submodule without any local modifications - `custom_targets.json` and `mbed_app.json` can already be passed from the outside, so that's the only thing left!

If I understand the mbed's tools correctly, using `Resources.add_ignore_patterns()` or `Resources.add_directory()` with a directory containing a `.mbedignore` should be enough.

### PR DESCRIPTION
**Pull request by mjbogusz**
As with the #29, this is not a very refined solution, but it works! ;)

Normally, the `.mbedignore` file is being read and applied all in one step (`Resources.add_directory()`, `tools/resources/__init__.py:429`), so in order to be able to 'override' the main `mbed-src/.mbedignore` one I've renamed it to `*.template` and use it as a fallback.
The other solution was to pass the `.mbedignore` path down there, but it seemed much more intrusive - the current solution barely touches the `tools` directory.

Fixes #28.

### CODE REVIEW

**Comment by multiplemonomials** [comment]
Hmm, I like the idea of this as it finally removes the one thing that requires modifying the submodule contents.  I wonder though, maybe it'd make sense to change the default behavior to have no mbedignore, and just add a section of the docs telling people to please, please create one to get the build time down to something sensible.  I like the idea of being compatible with the default Mbed feature of building everything, but I also really hate that feature which is why I added the default mbedignore...

**Comment by multiplemonomials** [comment]
Any way you could rebase on master @mjbogusz ?

**Comment by mjbogusz** [comment]
Sure, I'll push it soon.
Regarding the default mbedignore, maybe it should simply be a part of the `mbed-cmake-example-project` with a note in the docs and/or the `--help`?

**Comment by mjbogusz** [comment]
I've pushed a version without the `.mbedignore` and I'll push a PR to the `example-project` repo soon - if you prefer the in-repo template solution, I can push that version into this PR's branch.

**Comment by multiplemonomials** [comment]
OK I checked it out and it works great.  Thanks for adding this!

**Pull request merged**
